# Generated by Django 3.0.6 on 2020-08-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_name', models.CharField(max_length=100)),
                ('Question_id', models.CharField(max_length=100)),
                ('Question_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
