# Generated by Django 3.1 on 2020-08-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usr_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('usr_mail', models.EmailField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('usr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users')),
            ],
        ),
    ]
