# Generated by Django 3.1 on 2020-08-19 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_leaderboard_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 3, 46, 159977), verbose_name='Registered Time'),
        ),
    ]
