# Generated by Django 3.1 on 2020-08-19 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_users_regtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 9, 2, 580565)),
        ),
    ]
