# Generated by Django 3.1 on 2020-08-19 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200819_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 10, 33, 230192)),
        ),
    ]
