# Generated by Django 3.1 on 2020-08-19 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200819_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Question_id',
        ),
        migrations.AlterField(
            model_name='users',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 17, 59, 20, 590289)),
        ),
    ]
