# Generated by Django 3.1 on 2020-08-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200819_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='regTime',
            field=models.DateTimeField(verbose_name='Regitered Time'),
        ),
    ]
