# Generated by Django 3.0.4 on 2020-08-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200819_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='profile_pic',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
