# Generated by Django 3.0.4 on 2020-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_leaderboard_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
