# Generated by Django 3.0.4 on 2020-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='usr_name',
            field=models.TextField(max_length=500),
        ),
    ]
