# Generated by Django 3.1 on 2021-03-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_questions_totalcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_stamp', models.DateTimeField()),
                ('end_time_stamp', models.DateTimeField()),
            ],
        ),
    ]
