# Generated by Django 3.1 on 2021-04-08 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='uploadingTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Question Uploading Time'),
        ),
        migrations.AlterField(
            model_name='users',
            name='regTime',
            field=models.DateTimeField(verbose_name='Registered Time'),
        ),
    ]
