# Generated by Django 3.1 on 2021-04-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20210408_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='solved_questions',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
